### PR TITLE
Find Unique Elements Done

### PR DESCRIPTION
**Pull request by kylelaughlin**

### CODE REVIEW

**Comment by andrewek** [comment]
Nicely done. It hadn't occurred to me to use the counting method (where you use a hash to track how many times each thing occurs). That's a simpler method, at least at the outset, than the method I see most frequently, which is to build an array by checking each element to see if it occurs more than once, then removing all instances of that element if so.

Your method requires two passes (for an array of _n_ elements; inserting into a hash is O(1) complexity, which is pretty fast), ultimately yielding O(n) complexity (not bad).

The method I described above has a worst case run-time of O(n<sup>2</sup>).

(The way Big-O notation works -- for some arbitrarily large value of _n_, evaluate the stuff in the parentheses, e.g. _O(n<sup>2</sup>)_; the higher the result, the more complex.

O(1) is constant-time, that is, it takes the exact same amount of time regardless of how many elements exist.

O(n) is linear time

O(n<sup>2</sup>) is quadratic time, and so on.

There's also logarithmic time: O(log<sub>2</sup> n), which is slower than constant time but generally faster than linear time except for very small data sets.

Anyhow, I'm closing this out. Nice work.

**Comment by kylelaughlin** [comment]
After reading your comment I am doing some research on Big-O notation....I was writing out a long comment about how I thought it would be O(n<sup>2</sup>) but as I was typing it made sense.  To check my understanding: I use a nested loop (the each method) within another loop.  Since my inner loop only sets a variable via incrementing by 1 it yields constant time O(1). The outer loop sets a variable = 0, O(1) and then sets a hash key-value pair which would be O(n).  The second half of the algorithm iterates through a hash one time pushing to an array which is only O(n).  This would mean as n items are fed to the algorithm the time involved increase by n so it is linear, O(n)

**Comment by andrewek** [comment]
Exactly. and two O(n) algorithms, one after the other, resolve to O(n) (instead of O(2n) or O(4n + 7) or whatever else it might be; it's the exponent on _n_ that's important).

**Comment by kylelaughlin** [comment]
Groovy!  Thanks.

**Pull request closed without merging**
